version: "2.3"
services:

  devicemanagementservice:
    extends:
      file: docker-compose.base.yml
      service: devicemanagementservice
    container_name: devicemanagementservice
    build:
      context: ./devicemanagementservice
      dockerfile: Dockerfile
    image: vaskar/devicemanagementservice
    ports:
      - "8888:8888"
  device-client:
    extends:
      file: docker-compose.base.yml
      service: device-client  
    container_name: device-client
    build:
      context: ./device-client
      dockerfile: Dockerfile
    image: vaskar/device-client
    ports:
      - "3000:80"
